// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: first.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat string `protobuf:"bytes,1,opt,name=Chat,proto3" json:"Chat,omitempty"`
	Id   int32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *UserOne) Reset() {
	*x = UserOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOne) ProtoMessage() {}

func (x *UserOne) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOne.ProtoReflect.Descriptor instead.
func (*UserOne) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{0}
}

func (x *UserOne) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

func (x *UserOne) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat string `protobuf:"bytes,1,opt,name=Chat,proto3" json:"Chat,omitempty"`
	Id   int32  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *UserTwo) Reset() {
	*x = UserTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwo) ProtoMessage() {}

func (x *UserTwo) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwo.ProtoReflect.Descriptor instead.
func (*UserTwo) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{1}
}

func (x *UserTwo) GetChat() string {
	if x != nil {
		return x.Chat
	}
	return ""
}

func (x *UserTwo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ServerResOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
}

func (x *ServerResOne) Reset() {
	*x = ServerResOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerResOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResOne) ProtoMessage() {}

func (x *ServerResOne) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResOne.ProtoReflect.Descriptor instead.
func (*ServerResOne) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{2}
}

func (x *ServerResOne) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type ServerResTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
}

func (x *ServerResTwo) Reset() {
	*x = ServerResTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_first_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerResTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResTwo) ProtoMessage() {}

func (x *ServerResTwo) ProtoReflect() protoreflect.Message {
	mi := &file_first_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResTwo.ProtoReflect.Descriptor instead.
func (*ServerResTwo) Descriptor() ([]byte, []int) {
	return file_first_proto_rawDescGZIP(), []int{3}
}

func (x *ServerResTwo) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_first_proto protoreflect.FileDescriptor

var file_first_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a,
	0x07, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x07,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x77, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x4f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x54, 0x77,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x62, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x2c, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x65,
	0x12, 0x08, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x65, 0x1a, 0x0d, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x4f, 0x6e, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x2c, 0x0a,
	0x0d, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x54, 0x77, 0x6f, 0x12, 0x08,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x77, 0x6f, 0x1a, 0x0d, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x54, 0x77, 0x6f, 0x28, 0x01, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_first_proto_rawDescOnce sync.Once
	file_first_proto_rawDescData = file_first_proto_rawDesc
)

func file_first_proto_rawDescGZIP() []byte {
	file_first_proto_rawDescOnce.Do(func() {
		file_first_proto_rawDescData = protoimpl.X.CompressGZIP(file_first_proto_rawDescData)
	})
	return file_first_proto_rawDescData
}

var file_first_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_first_proto_goTypes = []interface{}{
	(*UserOne)(nil),      // 0: UserOne
	(*UserTwo)(nil),      // 1: UserTwo
	(*ServerResOne)(nil), // 2: ServerResOne
	(*ServerResTwo)(nil), // 3: ServerResTwo
}
var file_first_proto_depIdxs = []int32{
	0, // 0: Chat.SendToUserOne:input_type -> UserOne
	1, // 1: Chat.SendToUserTwo:input_type -> UserTwo
	2, // 2: Chat.SendToUserOne:output_type -> ServerResOne
	3, // 3: Chat.SendToUserTwo:output_type -> ServerResTwo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_first_proto_init() }
func file_first_proto_init() {
	if File_first_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_first_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_first_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_first_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerResOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_first_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerResTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_first_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_first_proto_goTypes,
		DependencyIndexes: file_first_proto_depIdxs,
		MessageInfos:      file_first_proto_msgTypes,
	}.Build()
	File_first_proto = out.File
	file_first_proto_rawDesc = nil
	file_first_proto_goTypes = nil
	file_first_proto_depIdxs = nil
}
